### PR TITLE
Adding more error information in case of an exception.

### PR DESCRIPTION
**Pull request by epacke**
This is just so we can easier identify issues with the script.

### CODE REVIEW

**Comment by epacke** [comment]
How about this?

image

**Comment by haughki** [comment]
any way to get a stack trace?

**Comment by haughki** [comment]
I guess "check the browser console' is the way to get the stack trace.... I
can live with that.

**Comment by epacke** [comment]
Most of the people using the tool won't understand a stack trace anyway. :)

**Pull request merged**
